WA 10
dmorbitzer/web-project pull request #11
Opened 2022-12-30 13:55 UTC by dstumpe

2023-01-02 14:33 UTC, bhecker approved these changes

2023-01-07 11:57 UTC, Swaggener approved these changes
Looks all good

2023-02-07 13:29 UTC, dmorbitzer requested changes

2023-02-07 13:29 UTC, dmorbitzer commented on src/main/java/de/fom/webapp/service/CardSetSelectorService.java
> +        PageRequest pageRequest = this.paginationService.createPageable(
Warum brauchen wir hier ein pageable? Es findet ja keine Paginierung mehr statt sondern es wird direkt das memory spiel gestartet.

2023-02-07 13:29 UTC, dmorbitzer commented on src/main/java/de/fom/webapp/controller/CardSetController.java
> +        );
Ich vermute wir brauchen noch ein Errorhandling, wenn ein Card Set geladen wir welches nicht existiert oder?

2023-02-07 13:29 UTC, dmorbitzer commented on src/test/java/de/fom/webapp/integration/controller/CardSetControllerTest.java
> +                .andExpect(status().isOk())
Wie oben beschrieben sollte es hier zu einem error kommen, also nicht OK(200) sonder Not Found(404)

2023-02-12 10:17 UTC, dmorbitzer approved these changes

2023-02-12 10:17 UTC, merged